name: Auto-format code on every PR

on:
  push:
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: autopep8
        uses: peter-evans/autopep8@v1.2.1
